language: node_js

node_js:
  - '4'
  - '5'
  - '6'

branches:
  - master

before_script:
  - npm install

script:
  - ls -al build/css/feathericon.css
  - ls -al build/css/feathericon.min.css
  - ls -al build/fonts/feathericon.eot
  - ls -al build/fonts/feathericon.svg
  - ls -al build/fonts/feathericon.ttf
  - ls -al build/fonts/feathericon.woff
  - ls -al build/scss/_feathericon.scss
  - ls -al build/svg/sprite.feathericon.svg

deploy:
  - provider: npm
    email: ${NPM_EMAIL}
    api_key: ${NPM_API_KEY}
    skip_cleanup: true
    on:
      branch: master
      repo: ${TRAVIS_REPO_SLUG}
  - provider: script
    script: bin/deploy.sh
    skip_cleanup: true
    on:
      branch: master

env:
  global:
  - GH_REF: github.com/feathericon/feathericon.git
  - secure: "r4v0i6bbW+Vd6TWQHc6COaK2MnWcUM+HSxRPFnwinv2BPTdGSWOOyTt9JaPUmkDfmNd3ZIs4k3HNL4liCgRbWLmEcpmBHVp/SATVGx+lKFRJM5Av+P5wXdNk3+SPno1Gb20IPxdZxIr4D+f1nkCExm+ss/aLoyqFK/UnoMPbTBYtRiUR/bgbs89js2beK6t3drguWNwsUN1yTsxCLnnShud2ggpSvwfw9qCDevQ9xGaEGk9rZOK8G3lDIxpYIoKTqxRUCbKLSjFV5WSVZ6duL679/iJNwO4qe/joQGwzVuTFK4i7S5LZZi9dAWH712kcBH9Id4HYSh3U6j4bRPh+prvyifqO9y31pgKQTFji8F39q46Hh383VplVvmuowFKtd/hbOzrgbU6l8B4hbiSfuf3qIpQEWyHE0IPedAw2dsMj+RwxBXWbX6cIJlq5z+teJZlkuELUopnRX2h2X9iIeSGyGzzJbQeNZI+/gwkxbyNFwk4cvE4fFDu5/XB/BK+8KLeM35w96Q6lNRYqJzXRQmdyED8W0zLWrAwh9R2aJAcd8skJ+c3KoUq9SXhnj/yOB4BJ7gpPYWgJnHDv3JRSpJNIfiiCP2ekeW4u6Nd6WVn0t7Po53nn09ezDvEfMSzjf7BQVugnuoM82jVtTQEpnWT/WLx7fwg6Fundpya5U8c="
